<?php

//TECH
define('SESSION_DATA_CONTAINER', 'webgk');


//USER
define('USER_GROUP_CODE_PARTNERS', 'PARTNERS');
define('USER_GROUP_CAN_VOTE_RESPECT_ID', 4);
define('USER_GROUP_CAN_VOTE_RATING_ID', 3);
define('USER_GROUP_REGISTERED_ID', 6);
define('CAPTCHA_PUBLIC', '6LcsgVspAAAAAJX0VQ7EK6BqMJMo5miuGr7bEKd2');
define('CAPTCHA_SECERET', '6LcsgVspAAAAAH_pm-YzqO5mwvCM0heJBfZ_F139');

//CATALOG
define('CATALOG_1C_IBLOCK_ID', 2);
define('CATALOG_1C_TP_IBLOCK_ID', 3);
define('NEW_CATALOG_IBLOCK_ID', 61);
define('NEW_CATALOG_TP_IBLOCK_ID', 62);

//SALE
define('ADD_2_BASKET_URL', '/catalog/add2basket.php');
define('MINIMAL_PRICE_FOR_FREE_DELIVERY_BASKET', 1000);
define('DELIVERY_COURIER_CUSTOM_ID', 8);
define('PAYER_TYPE_PHYS', 1);
define('PAYER_TYPE_JUR', 2);