<?php

define('USER_GROUP_CODE_PARTNERS', 'PARTNERS');
define('USER_GROUP_CAN_VOTE_RESPECT_ID', 4);
define('USER_GROUP_CAN_VOTE_RATING_ID', 3);
define('USER_GROUP_REGISTERED_ID', 6);

define('CATALOG_1C_IBLOCK_ID', 6);
define('CATALOG_1C_TP_IBLOCK_ID', 7);

define('NEW_CATALOG_IBLOCK_ID', 8);
define('NEW_CATALOG_TP_IBLOCK_ID', 9);
